### ISSUE TITLE
minification fail: doctype object has no attribute name

### ISSUE THREAD

**Issue by digitalvapor** [rdegges/pelican-minify#10]
Hi, I think that possibly some of the restructured text posts (usually I use markdown) on my blog or iPython notebooks may be giving the following error. It could be correlation and not causation though, since I just know it worked in the past before I started implementing them. I traced about in [htmlmin](https://github.com/mankyd/htmlmin), but didn't immediately see the source of the issue.

```
CRITICAL: HTML Minification failed: 'Doctype' object has no attribute 'name'
```

When I find out more I will let you know, cheers - Tom

**Comment by rdegges** [comment]
Hmm, that sounds like it might be unrelated to minification -- but please keep me updated! I'd love to know what the root issue is, and make sure that if it's something breaking here I can fix it for ya! <33

**Comment by abr4xas** [comment]
issue example:

```html
<!DOCTYPE html>
<html lang=en>
  <head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content=IE=edge>
    <meta name=viewport content=width=device-width, initial-scale=1>
    <title>Test Template</title>
  </head>
  <body>
    <h1>Hello, world!</h1>
  </body>
</html>
```
This plugin remove all ```"``` from meta tag :(

**Comment by rdegges** [comment]
Hmm, this looks like an upstream issue. When a new library release comes out I'll merge it in and hopefully get a fix.
